name: Deploy STAGING (beta.absteelsolutions.se)

on:
  push:
    branches: [ "main", "dev" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build

      - name: Add .htaccess
        run: |
          cat > dist/.htaccess << 'EOF'
          <IfModule mod_rewrite.c>
          RewriteEngine On
          RewriteCond %{HTTPS} !=on
          RewriteRule ^ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]
          RewriteBase /
          RewriteCond %{REQUEST_FILENAME} !-f
          RewriteCond %{REQUEST_FILENAME} !-d
          RewriteRule ^ index.html [L]
          </IfModule>
          EOF

      - name: Deploy via FTPS
        uses: SamKirkland/FTP-Deploy-Action@4.3.5
        with:
          server: ${{ secrets.FTP_HOST }}
          port: ${{ secrets.FTP_PORT }}
          username: ${{ secrets.FTP_USER_STAGING }}
          password: ${{ secrets.FTP_PASS_STAGING }}
          protocol: ftps
          local-dir: dist/
          server-dir: /
          state-name: deploy-cache
          dangerous-clean-slate: true
